### ISSUE TITLE
Lita 4 Support?

### ISSUE THREAD

**Issue by MattMencel** [josqu4red/lita-redmine#1]
Any chance you could release a new version that works with Lita 4?

**Comment by josqu4red** [comment]
I didn't have a chance to use Lita 4 yet. Could you give more details about the issue ?

**Comment by MattMencel** [comment]
The plugin won't install because it's lita requirement in the gemspec only allows v3.  Maybe just fixing the requirement to include v4 will fix it, but there are some changes in v4 so possibly not.

**Comment by josqu4red** [comment]
I just updated code & specs to match Lita 4's new features.
lita-redmine v0.0.2 pushed to Rubygems.

**Comment by MattMencel** [comment]
Thanks for the quick fix.  Tested and it works great here...
